spring:
  # application:
  #   name: api_backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/yuapi
    url: jdbc:mysql://192.168.101.65:3306/api
    username: root
    #    password: 123456
    password: mysql
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  # redis 配置
  redis:
    port: 6379
    host: 192.168.101.65
    password: redis
    database: 0
  rabbitmq:
    host: 192.168.101.65
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: guest # 用户名
    password: guest # 密码
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
server:
  port: 7529
  servlet:
    context-path: /api
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
#    session:
#      cookie:
#        domain: api-backend.tempeisite.xyz
#        max-age: 2592000
#  address: 0.0.0.0
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:mapper/*.xml
api:
  client:
    access-key: zhj
    secret-key: abcd
# dubbo:
#   application:
#     name: dubbo-springboot-demo-provider
#   protocal:
#     name: dubbo
#     port: -1
#   registry:
#     id: nacos-registry
#     address: nacos://localhost:8848?namespace=api_dev
#     group: dubbo

canal:
  destination: heima # canal实例名称，要跟canal-server运行时设置的destination一致
  server: 192.168.101.65:11111 # canal地址

xxl:
  job:
    admin:
      addresses: http://192.168.101.65:8088/xxl-job-admin
    executor:
      appname: apiBackend-job
      address:
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken: default_token

oss:
  accessKey:
  secretKey:
  bucket:
  website:

wx:
  open:
    appId: wxed9954c01bb89b47
    secret: a7482517235173ddb4083788de60b90e
    redirectUrl: http://localhost:8160/user/wxLogin
